project:
  type: website

website:
  title: "Hareesh Kolluru"
  site-url: "https://hareeshkolluru.github.io"

  navbar:
    title: "Hareesh Kolluru"
    left:
      - text: "Posts"
        href: index.qmd
      - text: "Archive"
        href: journal.qmd
      - text: "About"
        href: about.qmd
      - text: "Work"
        href: work.qmd
      - text: "Contact"
        href: contact.qmd
    tools:
      - icon: sun
        menu:
          - text: "Light"
            theme: "light"
          - text: "Dark"
            theme: "dark"
          - text: "Auto"
            theme: "auto"

format:
  html:
    theme:
      light: [default, custom.scss]
      dark: [default, custom.scss]
    css: custom.scss
    page-layout: article
    toc: false
    code-block-background: true